### PR TITLE
Working dir should relativize to an empty string

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Awesome, thanks

**Comment by segiddins** [comment]
Thanks! Would be awesome to see this make it upstream, since it would obviate the need for https://github.com/atom/fuzzy-finder/issues/105

**Comment by izuzak** [comment]
> Would be awesome to see this make it upstream, since it would obviate the need for the `is ''` check in atom/fuzzy-finder#105

@kevinsawicki Could we bump the version of git-utils to help that effort? ^^^^

**Comment by kevinsawicki** [comment]
> Could we bump the version of git-utils to help that effort?

Published `3.0.1` with this fix.

**Pull request merged**
