### PR TITLE
🌲 Update libgit2 v0.26.0

### PR DESCRIPTION
**Pull request by billybonks**
Update libgit2 to version 0.26 so that `git_repository_open_ext` method supports work trees 🌴 🎄 🌳 🌲 :man_health_worker: 

New and deleted files
screen shot 2017-06-22 at 3 38 36 pm

### CODE REVIEW

**Comment by billybonks** [comment]
i seem to have broken submodules :<. but tests work well

screen shot 2017-06-22 at 3 38 50 pm

**Comment by billybonks** [comment]
The submodule is part of the test suite, but we install using --recursive so not sure how to ignore it https://github.com/libgit2/libgit2/commit/2270ca9f8feecf93fe39a02a6fbde90a22c1a665

**Comment by billybonks** [comment]
@atom/maintainers

**Comment by billybonks** [comment]
@joshaber

**Comment by vcanales** [comment]
Hi all. Any updates on this?

**Comment by billybonks** [comment]
still waiting on advice from the core team for https://github.com/atom/git-utils/pull/77#issuecomment-310557520

**Comment by bbugh** [comment]
@kevinsawicki @zcbenz @gjtorikian any chance y'all can take a look at this? It's really bothersome in Atom not having worktree support. Sounds like @billybonks just needs advice on the submodule.

**Comment by gjtorikian** [comment]
👋 I haven't done work on this project in some time. cc @atom/core

**Comment by vcanales** [comment]
From what [I’ve found](https://github.com/libgit2/libgit2/issues/4274) we’re not supposed to pull dependencies like this, ie. initializing submodules that include libgit2’s tests. 

Moving to something like https://github.com/libgit2/node-gitteh seems a bit over the top, so I guess waiting for advice is what we have.

**Comment by billybonks** [comment]
Two ideas I have
1 - fork the repo and just remove that test ( would require more maintenance from atom so quite not ideal)
2 - import the library without submoduling libgit2. ( not sure if this is possible)

**Comment by vcanales** [comment]
Ok, so I've made some progress. On `.travis.yml`:

```
git:
  depth: 10
  submodules: false

before_install:
  - git submodule update --init
```

Since we don't really need any submodules from `libgit2` (tested on current `master` https://travis-ci.org/vcanales/git-utils/builds/326919327), we can skip the `--recursive` that travis adds by default.

There issue has changed though, while building deps on @billybonks' branch + the submodules modification:

```
  CC(target) Release/obj.target/libgit2/deps/libgit2/src/iterator.o
../deps/libgit2/src/iterator.c:1459:44: error: no member named 'st_ctimespec' in 'struct stat'
        iter->entry.ctime.nanoseconds = entry->st.st_ctime_nsec;
                                        ~~~~~~~~~ ^
../deps/libgit2/src/unix/posix.h:27:24: note: expanded from macro 'st_ctime_nsec'
# define st_ctime_nsec st_ctimespec.tv_nsec
                       ^
../deps/libgit2/src/iterator.c:1462:44: error: no member named 'st_mtimespec' in 'struct stat'
        iter->entry.mtime.nanoseconds = entry->st.st_mtime_nsec;
                                        ~~~~~~~~~ ^
../deps/libgit2/src/unix/posix.h:26:24: note: expanded from macro 'st_mtime_nsec'
# define st_mtime_nsec st_mtimespec.tv_nsec
                       ^
2 errors generated.
```

**Comment by vcanales** [comment]
This got it building: https://travis-ci.org/vcanales/git-utils/builds/326929271 -- The MTIME flag defined was initially only for MacOS, and the linux version is different. Check https://github.com/nodegit/nodegit/blob/master/vendor/libgit2.gyp for a reference

https://github.com/billybonks/git-utils/compare/worktrees...vcanales:worktrees

**Comment by billybonks** [comment]
@vcanales nice, thanks for digging into it. though the other issue is that atom build.sh does a recursive pull on submodules. when I made this pr I tried to use the branch when building a custom atom for myself and it couldn't build for the same reason Travis couldn't build.

**Comment by vcanales** [comment]
@billybonks I'll take a look later! Thanks for bringing that up

**Comment by bbugh** [comment]
Awesome, thank you for looking at this! It looks like good progress. 

So many of Atom's important features don't work in worktrees, most importantly the "Exclude VCS Ignored Paths" setting doesn't work, which means that fuzzy-finder doesn't ignore VCS-ignored files. 

This results in fuzzy-finder searching giant useless folder structures like `node_modules` and `tmp/cache`. It makes it almost unusable in Atom for some projects, and I'm willing to bet it's why some people report the issue with fuzzy finder (like #89)

**Comment by vcanales** [comment]
@bbugh it's a bit surprising that this is not getting more attention! Worktrees are one of the biggest changes to git and they're not even that recent. I've been looking at reproducing the problem that @billybonks mentioned, but this has turned out to be way less simple that the previous stab. I'll keep trying though!

**Comment by billybonks** [comment]
@atom/core

**Comment by daviwil** [comment]
Hey folks!  Trying to get a read on where we're at with this PR.  Can someone summarize what the outstanding issues are that would block us from merging this?  Thanks a bunch!

**Comment by vcanales** [comment]
> Can someone summarize what the outstanding issues are that would block us from merging this?

My take is that the issue at the base is recursively updating and initializing submodules on build, as @billybonks points out:

> the other issue is that atom build.sh does a recursive pull on submodules. when I made this pr I tried to use the branch when building a custom atom for myself and it couldn't build for the same reason Travis couldn't build.

[The folks at `libgit2` explain:](https://github.com/libgit2/libgit2/issues/4274#issuecomment-309578237)

> We explicitly have test resources that have submodules that should not be initialized - these are our test resources, after all. In particular, we have (intentionally) broken repositories with (intentionally) broken submodules so that we can test these broken configurations.
>
> If you're (manually) running git submodule ... then my encouragement would be for you to not do that.

We've already removed this issue from this module's build, but atom's build fails because of the same issue.

**Comment by daviwil** [comment]
@vcanales thanks a lot for the summary, that was helpful!  So the last remaining issue is that Atom build's use of `git submodule update --init` causes this problem to appear.  Let me see if there's anything we can do about that.

**Comment by daviwil** [comment]
@vcanales I don't actually see a submodule pull step in any of Atom's build or CI scripts, could you point me to the script that exhibits this issue?

**Comment by vcanales** [comment]
> @vcanales I don't actually see a submodule pull step in any of Atom's build or CI scripts, could you point me to the script that exhibits this issue?

I was able to reproduce the issue by checking out this branch and building node based on it -- I also didn't find where the exact dependency is being pulled though :(

**Comment by daviwil** [comment]
Just tried building Atom with this branch npm link'ed, seems to work fine.  I think I'll go ahead and merge this and try to publish it for use in Atom.  If anything goes wrong we can always ship another update :)

Huge thanks to @billybonks and @vcanales for their work on this PR!

**Comment by daviwil** [comment]
Submitted this as https://github.com/atom/atom/pull/16799 to ensure we don't run into any CI issues there :)

**Comment by billybonks** [comment]
HORRAY Thanks @daviwil

**Pull request merged**
