### PR TITLE
Upgrade libgit2 to 0.24.2

### PR DESCRIPTION
**Pull request by niw**
To address #70, upgrade `libgit2` to 0.24.0.

### CODE REVIEW

**Comment by niw** [comment]
Just tested this patch with Atom.app, still Atom.app may crash with other issue in `libgit2` with git repository using index version 4. Even though, it might be good idea to have this patch to not crash `git-utils` by opening such git repository, however, this can't be a solution for atom/atom#11225.

**Comment by niw** [comment]
Updated `libgit2` to **0.24.1**. Sorry about the branch name that said 0.24.0. I can't change branch name to update this pull request.

**Comment by tgandrews** [comment]
There is now a `0.24.2` which fixes #73

**Comment by niw** [comment]
The commit 8dfc25b is a nasty workaround for the error occurs on Travis-CI environment, which is using npm 0.10 and clang-3.4. I'm not sure if we should have this commit or not, but to make things green, I put it for now.

**Comment by tgandrews** [comment]
What can I do to help test this?

**Comment by rossburton** [comment]
I really need this to merge as due to our .gitignore layout I can't use cmd-p at all thanks to #73.    Who do I need to send beer/coffee/flowers to?

**Comment by 50Wliu** [comment]
I've notified the team.

**Comment by damieng** [comment]
We should bump this to 0.24.3 to address the CVE issues reported on libgit2.

**Pull request merged**
